{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "registration.serviceAccountName" . }}
  labels:
{{ include "registration.labels" . | indent 4 }}
{{- end -}}
